Allow the User to Unselect a Move
ZenitechSoftware/planning-chess pull request #189
Opened 2023-01-01 15:48 UTC by jbartka

2023-01-05 08:35 UTC, jvalatkevicius requested changes

2023-01-05 08:35 UTC, jvalatkevicius commented on services/app/src/components/gameStatus/GameInfo.jsx
> +        {/* <img src={CheckMark} className="game-info-icon" alt="players done icon" /> */}
Why is this commented?

2023-01-05 08:35 UTC, jvalatkevicius commented on services/app/src/components/player/bouncingDots/styles.css
> +body {
This applies style to body tag, which is global, do we really need this? If we do, it should be in some other place, not next to bouncingDots styles.

2023-01-05 08:35 UTC, jvalatkevicius commented on services/app/src/components/player/bouncingDots/styles.css
> +  /* flex-grow: 1; */
remove comments

2023-01-05 08:35 UTC, jvalatkevicius commented on services/app/src/components/team/TeamMember.jsx
> +    { (status === playerStatuses.FigurePlaced && !isAllTurnsMade) && <div className="team-list-item-icon" alt="player done icon"> <BouncingDots/></div>}
Lets introduce a new component for player status and move all the logic related to user status display into that component.

2023-01-05 08:35 UTC, jvalatkevicius commented on services/app/src/components/player/bouncingDots/BouncingDots.jsx
> +import React from "react";
Lets rename the component (and the file) to `LoaderDots`.

2023-01-05 08:35 UTC, jvalatkevicius commented on services/app/src/components/gameFooter/GameFooterButtons.jsx
> +        onClick={clearBoard}
If I understand correctly, the button clears the board for all the players, however, when I unselect my move, I would expect that only my move was reverted.

2023-01-05 08:35 UTC, jvalatkevicius commented on services/app/src/components/player/bouncingDots/BouncingDots.jsx
> +        <div></div>
You can add some classname for this div, to make it more readable, e.g. `dot`.

2023-02-07 06:28 UTC, jvalatkevicius approved these changes

2023-04-10 18:12 UTC, closed without merging

2023-04-10 18:12 UTC, jbartka commented
Done Already