feature/plan-115-web-copy-game-link
ZenitechSoftware/planning-chess pull request #207
Opened 2023-02-02 15:52 UTC by RutaB98

2023-02-03 06:18 UTC, jvalatkevicius requested changes

2023-02-03 06:18 UTC, jvalatkevicius commented on E2E/pageObjects/game.page.ts
> +    I.waitForElement(locator.text.linkCopiedToClipboard, 7);
Why are you using different explicit timeouts here? (10 and 7). I would expect default codecept timeouts to be enough.

2023-02-03 06:18 UTC, jvalatkevicius commented on E2E/tests/copyLink.test.ts
> +Feature('Copy link');
This seems to be missing test that would check if the link was actually copied into the cliipboard.

2023-02-03 06:18 UTC, jvalatkevicius commented on E2E/pageObjects/game.page.ts
> +    linkCopiedToClipboard: '//*[contains(text(), "Link copied to clipboard")]',
Would it work, if you removed `contains` function and leave only exact match by text?

2023-02-03 06:18 UTC, jvalatkevicius commented on E2E/pageObjects/game.page.ts
> +    copyLink: '//*[contains(text(), "Copy Link")]',
Same as above

2023-02-03 06:19 UTC, jvalatkevicius requested changes

2023-02-03 06:19 UTC, jvalatkevicius commented on E2E/package-lock.json
> -        "eslint-config-prettier": "^8.3.0",
Why these were removed?

2023-02-03 11:28 UTC, KristinaKrev commented on E2E/pageObjects/game.page.ts
> +    copyLink: '//*[contains(text(), "Copy Link")]',
There are two elements with "Copy link" text on page, doesn't this find both of them?

2023-02-03 11:36 UTC, KristinaKrev commented on E2E/pageObjects/game.page.ts
> +    I.waitForInvisible(locator.text.linkCopiedToClipboard, 7);
Based on Acceptance criteria, tooltip should disappear after 2 sek, is this timeout correct?

2023-02-06 14:34 UTC, jvalatkevicius requested changes

2023-02-06 14:34 UTC, jvalatkevicius commented on E2E/assertions/copyLinkAssert.ts
> +      let currentUrl = await I.grabCurrentUrl();
why `let`?

2023-02-06 14:34 UTC, jvalatkevicius commented on E2E/assertions/copyLinkAssert.ts
> +        let clipboardText = await page.evaluate("navigator.clipboard.readText()");
why `let`?

2023-02-06 14:34 UTC, jvalatkevicius commented on E2E/assertions/copyLinkAssert.ts
> +    async checkIfTheLinkWasCopied () {
Why was this moved into a separate file? Cannot we do this exact thing in the test itself?

2023-02-06 14:34 UTC, jvalatkevicius commented on E2E/assertions/copyLinkAssert.ts
> +        await browserContext.grantPermissions(['clipboard-write', 'clipboard-read']);
is the `clipboard-write` permission needed here?

2023-02-06 14:34 UTC, jvalatkevicius commented on E2E/assertions/copyLinkAssert.ts
> +        await browserContext.grantPermissions(['clipboard-write', 'clipboard-read']);
Are the permissions needed in the first place?

2023-02-06 14:34 UTC, jvalatkevicius commented on E2E/pageObjects/game.page.ts
> +    copyLink: locate('//*[text() = "Copy Link"]').at(1),
What does `at(1)` do?

2023-02-07 11:20 UTC, jvalatkevicius approved these changes

2023-02-07 12:17 UTC, KristinaKrev approved these changes

2023-02-07 12:26 UTC, merged