PLAN-159 (Safari Font Update)
ZenitechSoftware/planning-chess pull request #240
Opened 2023-03-27 17:32 UTC by jbartka

2023-03-28 04:34 UTC, jvalatkevicius commented
Why package-lock has changed?

2023-03-28 04:34 UTC, jvalatkevicius requested changes
Why package-lock has changed?

2023-03-30 20:48 UTC, jbartka commented
> Why package-lock has changed?

I did npm install before running bootstrap and dev

2023-03-31 06:38 UTC, jvalatkevicius approved these changes

2023-03-31 07:02 UTC, merged