PLAN-144 added data-testid attributes
ZenitechSoftware/planning-chess pull request #242
Opened 2023-03-29 07:46 UTC by RutaB98

2023-03-29 11:08 UTC, AndzejIlj requested changes

2023-03-29 11:08 UTC, AndzejIlj commented on services/app/src/components/avatar/CustomAvatar.jsx
> +      data-testid="profile-picture"
There will probably be more than 1 custom avatar in the game. You don't want all of them to have the same id

2023-03-29 11:08 UTC, AndzejIlj commented on services/app/src/components/team/VoterScoreIcon.jsx
> +    <span data-testid="voter-score" className={classNames('team-list-voter-score padding-x-s padding-y-xs font-size-xs border-r-20', {
Same as with others.

2023-03-30 13:27 UTC, jvalatkevicius submitted a review, later dismissed

2023-03-31 06:39 UTC, jvalatkevicius approved these changes

2023-03-31 06:40 UTC, AndzejIlj approved these changes

2023-03-31 06:40 UTC, merged