Place a figure on a board
ZenitechSoftware/planning-chess pull request #36
Opened 2022-01-15 14:29 UTC by albekruz

2022-01-16 13:20 UTC, jvalatkevicius commented on services/app/src/pages/game/Game.jsx
> +        <ChessBoard numberOfColumns={6} numberOfRows={6} />
numberOfColumns ir numberOfRows yra aprasyti constantu faile `services/app/src/constants/board.js`

2022-01-16 13:39 UTC, jvalatkevicius requested changes

2022-01-16 13:39 UTC, jvalatkevicius commented on services/app/src/components/chessBoard/ChessBoard.jsx
> +           <td
Manau reiketu `Tile` iskelti i atkira komponenta ir padaryti taip
```
const ChessBoard = () => {
  const { placeItemOnBoard, board } = useContext(ChessBoardContext)

  return (
    <table id="chess-board">
      {board.map((row, rowIndex) => (
        <tr key={rowIndex}>
          {row.map((tile, columnIndex) => (
            <Tile
              key={tileIndex}
              attribute={tile.attribute}
              items={tile.items}
              onClick={placeItemOnBoard}
              row={rowIndex}
              column={columnIndex}
            />
          ))}
        </tr>
      ))}
    </table>
  );
};
```

Kur `Tile.jsx`:
```
const Tile = ({ attribute, items, onClick, row, column }) => {
  const someSensibleNameThatDescribesWhatThisConditionMeans = () => {
    return !tile.attribute && row !== board.length - 1 && column !== 0
  }

  const _onClick = useCallback(() => {
    onClick(row, column)
  }, [onClick]);

  return (
    <td
      onClick={_onClick}
      role='presentation'
      className={
        classNames({
          'black-tile': tile.isFilled,
          'white-tile': someSensibleNameThatDescribesWhatThisConditionMeans(),
        })
      }
    >
      {attribute || items}
    </td>
  )
}
```

cia classNames yra package'as, kuris is true/false objekto sulipdo klasiu vardus - https://www.npmjs.com/search?q=classNames

2022-01-17 10:37 UTC, raywiis requested changes

2022-01-17 10:37 UTC, raywiis commented on services/app/src/hooks/useChessBoard.js
> +            ? numberOfColumns - rowIndex
why not get rid of one of the ternaries and explicitly have a row for numbers?
```
[
  ...Array(numberOfRows).keys().map(() => etc),
  [...[...Array(numberOfRows).keys()].map(k => k + 1))
]
```
Or just
```
[
  ...Board stuff,
  [1, 2, 3, 4, 5, 6, 7, 8]
]
```

2022-01-17 10:37 UTC, raywiis commented on services/app/src/hooks/useChessBoard.js
> +            ? numberOfColumns - rowIndex
Same with the symbol for columns
just add the symbol as an element before spreading the rest of the board stuff in and you won't need a 3 story ternary.

2022-01-17 10:37 UTC, raywiis commented on services/app/src/hooks/useChessBoard.js
> +      [...Array(numberOfColumns + 1).keys()].map((_tile, tileIndex) => ({
Python has a `range` function, you could make yourself something similar here, a function that returns an array from x to y

2022-01-17 10:40 UTC, raywiis commented on services/app/src/hooks/useChessBoard.js
> +            ? numberOfColumns - rowIndex
My bad: row for symbols, column for numbers. But the point is the same - have explicit elements to simplify the ternary.

2022-01-19 13:22 UTC, raywiis approved these changes

2022-01-19 17:48 UTC, jvalatkevicius approved these changes

2022-01-24 08:22 UTC, raywiis commented
@tautvydasLiekis I think this needs your review

2022-01-24 08:27 UTC, albekruz commented
> @tautvydasLiekis I think this needs your review

This ticket is still "in progress" as we decide to add some additional functionalities on the last catch-up meeting.

2022-02-27 12:57 UTC, albekruz commented on services/app/src/constants/board.js
> +export const PIECES = ['pawn', 'knight', 'bishop', 'rook', 'king', 'queen'];
Kol kas neturim fronte .ts loaderio webpacke, tai reikėtu papildomai į webpacka instaliuot loaderius, kas nėra susiję su užduotim, tai ateityje jeigu nuspręsim įdėti .ts į frontą, tuomet bus galima pridėti ir enum'us.

2022-03-06 13:29 UTC, albekruz commented on services/api/src/game/game.service.ts
> +    turns.push(payload);
After clicking on submit button, player will not be able to update his figure position

2022-03-07 13:19 UTC, arvurb requested changes

2022-03-07 13:19 UTC, arvurb commented on services/api/src/domain/player.ts
> +  status: 'done' | 'active';
use enum

2022-03-10 07:49 UTC, arvurb approved these changes

2022-03-10 07:53 UTC, arvurb submitted a review, later dismissed

2022-03-11 17:58 UTC, jvalatkevicius approved these changes

2022-03-11 18:03 UTC, jvalatkevicius commented on services/app/src/components/chessBoard/ChessBoard.jsx
> +/* eslint-disable no-console */
Why is this here?

2022-03-15 15:20 UTC, arvurb approved these changes

2022-03-15 15:22 UTC, merged

2022-03-15 16:44 UTC, jvalatkevicius approved these changes