Let play the game when more than 1 player joins
ZenitechSoftware/planning-chess pull request #59
Opened 2022-05-16 09:16 UTC by albekruz

2022-05-16 10:13 UTC, arvurb requested changes

2022-05-16 10:13 UTC, arvurb commented on services/app/src/contexts/ChessBoardContext.jsx
> +  const { turns, myTurn, movedBy, users, playerDeleted } = useWebSockets();
I would prefer to call it `players`

2022-05-16 11:41 UTC, jvalatkevicius requested changes

2022-05-16 11:41 UTC, jvalatkevicius commented on services/app/src/contexts/ChessBoardContext.jsx
> +  useEffect(() => {
I think `useMemo` would fit better here:
```
const canPlay = useMemo(() => players.length > 0, [players]);
```
I'm not sure if the `playerDeleted` needs to be included in the dependencies. It is included in the `useEffect` deps, but I feel like if the player is deleted, the `players` list should be updated as well, so the `playerDeleted` might be redundant

2022-05-16 11:41 UTC, jvalatkevicius commented on services/app/src/components/team/Team.jsx
> +  players: PropTypes.arrayOf(userPropType).isRequired,
If we are renaming `user` to `player`, we should also rename the `userPropType` accordingly.

2022-05-20 08:14 UTC, arvurb approved these changes

2022-05-23 09:46 UTC, Augmas approved these changes

2022-06-09 06:52 UTC, jvalatkevicius submitted a review, later dismissed

2022-06-09 07:41 UTC, jvalatkevicius approved these changes

2022-06-09 07:58 UTC, merged