assigns the color to each player
ZenitechSoftware/planning-chess pull request #78
Opened 2022-06-30 05:39 UTC by jbartka

2022-06-30 08:12 UTC, jvalatkevicius requested changes

2022-06-30 08:12 UTC, jvalatkevicius commented on services/api/src/messaging/players.service.ts
> +// @ts-ignore
Why is this needed here?

2022-06-30 08:12 UTC, jvalatkevicius commented on services/app/src/prop-types/player.js
> +  // eslint-disable-next-line react/forbid-prop-types
`color` is used in `TeamMember` prop types. Would it be possible to reuse same type here and get rid of this ignore?

2022-07-07 07:27 UTC, arvurb commented
Please fix tests and lint errors. Otherwise looks good!

2022-07-15 07:37 UTC, jvalatkevicius approved these changes

2022-07-15 07:56 UTC, merged